//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_CLIENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserR
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string LastKnownIP { get; set; }
        public string PreName { get; set; }
        public string LastName { get; set; }
    }
}
